// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddContact(arg1:string,arg2:string):Promise<void>;

export function DeleteContact(arg1:string):Promise<void>;

export function GetChatHistory(arg1:string):Promise<Array<main.MessageInfo>>;

export function GetChatReactions(arg1:string):Promise<Record<string, Array<main.ReactionInfo>>>;

export function GetContacts():Promise<Array<main.ContactInfo>>;

export function GetLocalUser():Promise<main.ContactInfo>;

export function GetOnlineUsers():Promise<void>;

export function GetUnreadCount(arg1:string):Promise<number>;

export function Register(arg1:string):Promise<main.ContactInfo>;

export function SearchUsers(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendReaction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendTyping(arg1:string):Promise<void>;
