// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContact(arg1, arg2) {
  return window['go']['main']['App']['AddContact'](arg1, arg2);
}

export function ArchiveContact(arg1, arg2) {
  return window['go']['main']['App']['ArchiveContact'](arg1, arg2);
}

export function BlockContact(arg1, arg2) {
  return window['go']['main']['App']['BlockContact'](arg1, arg2);
}

export function ChangeUsername(arg1) {
  return window['go']['main']['App']['ChangeUsername'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteMessagesForEveryone(arg1, arg2) {
  return window['go']['main']['App']['DeleteMessagesForEveryone'](arg1, arg2);
}

export function DeleteMessagesLocal(arg1) {
  return window['go']['main']['App']['DeleteMessagesLocal'](arg1);
}

export function EditMessageContent(arg1, arg2) {
  return window['go']['main']['App']['EditMessageContent'](arg1, arg2);
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetChatReactions(arg1) {
  return window['go']['main']['App']['GetChatReactions'](arg1);
}

export function GetContact(arg1) {
  return window['go']['main']['App']['GetContact'](arg1);
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetLocalUser() {
  return window['go']['main']['App']['GetLocalUser']();
}

export function GetOnlineUsers() {
  return window['go']['main']['App']['GetOnlineUsers']();
}

export function GetUnreadCount(arg1) {
  return window['go']['main']['App']['GetUnreadCount'](arg1);
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function MarkMessagesRead(arg1) {
  return window['go']['main']['App']['MarkMessagesRead'](arg1);
}

export function PinContact(arg1, arg2) {
  return window['go']['main']['App']['PinContact'](arg1, arg2);
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function SearchMessages(arg1, arg2) {
  return window['go']['main']['App']['SearchMessages'](arg1, arg2);
}

export function SearchUsers(arg1) {
  return window['go']['main']['App']['SearchUsers'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendReaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendReaction'](arg1, arg2, arg3);
}

export function SendTyping(arg1) {
  return window['go']['main']['App']['SendTyping'](arg1);
}
